version: '3.7'
services:
  al_test:
     image: al_test:20-03-25
     volumes:
     - ./outer:/root/al_test
     restart: always
     ports:
       - 80:80
  db:
    image: mysql:laster
    environment:
      MYSQL_ROOT_PASSWORD: "test1234"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3307:3306"       
       
